title: Heeyeon Kim  # You can add your name here

logo: /assets/myProfileCircleSmall.png # Use a relative path to logo image 

description: HCI Researcher # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: heeyeona1@gmail.com # Allow visitors to contact you
